### ISSUE TITLE
[Question] Shared storage between windows and linux node on single cluster deployment

### ISSUE THREAD

**Issue by dsfrederic** [Azure/AKS-Edge#104]
**Describe scenario**
I need to access the same data first on the windows node. Then I would like to do some transformations with a pod that's located on the Linux node. Afterwards the windows node takes that data and sends it to a storage account in Azure. 

**Question**
What would be the best method to do this?

**First attempts**
1. Local path -> Doesn't make sense since the local path on windows node will not have the same data as the one in linux node. 
2. NFS on windows host -> Seems to not be accessible from within the cluster

**Comment by fcabrera23** [comment]
Hi @dsfrederic,

Thanks for reaching out. A couple of thoughts on your scenario

1) Local path is not an option because of the reason you mentioned. Also, currently, we do not support local path storage on the Windows node. 

2) NFS on a Windows host could be an option, but currently, we do not support NFS storage binding on the Windows node. You could implement an NFS connection directly on the container, although it's something we do not recommend

3) Use communication between pods, something like MQTT or Kafka. You could also use a KV store but will depend on the size of your files

4) We plan to bring support for file/folder sharing in the future, similar to [Share a Windows folder with Azure IoT Edge for Linux on Windows](https://learn.microsoft.com/en-us/azure/iot-edge/how-to-share-windows-folder-to-vm?view=iotedge-1.4). Would this be something you are looking forward?

Thanks,
Francisco

**Comment by dsfrederic** [comment]
> 4\. We plan to bring support for file/folder sharing in the future, similar to [Share a Windows folder with Azure IoT Edge for Linux on Windows](https://learn.microsoft.com/en-us/azure/iot-edge/how-to-share-windows-folder-to-vm?view=iotedge-1.4). Would this be something you are looking forward?

This would be immensely helpful. Is this something we can test in beta?

**Comment by dsfrederic** [comment]
@fcabrera23 please reopen.
