### ISSUE TITLE
New-AksEdgeDeployment overwrites kubeconfig

### ISSUE THREAD

**Issue by pbering** [Azure/AKS-Edge#125]
**Describe the bug**
When deploying with `New-AksEdgeDeployment` the current kubeconfig is overridden instead of the cluster connection is just added.

**To Reproduce**
1. Connect to any cluster, verify that it works and its added to your [kubeconfig](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig)
2. Run `New-AksEdgeDeployment` ...
3. Now the connection from 1 is gone and only the new connection is present

**Expected behavior**
I expect ASK EE to leave my current connections in kubeconfig alone and just add the new connection and switch to it. This can be done using `kubectl config set cluster` (see <https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/#define-clusters-users-and-contexts>).

**Environment (please complete the following information):**
 - AKS Edge Essentials Version [e.g. 3.22] **== 1.2.414**
 - Kubernetes version [e.g. 1.24.3] **== K8S 1.25.4**
 - Windows Host OS (please complete the following information):
    - Edition: [e.g. Professional, IoT Enterprise, Server, etc] **== Enterprise**
    - Version: [e.g. build 17763] **== 22H2, 22621.1848**
    - Virtual Machine: [eg. Azure VM, Local VM, Other, None] **== no**

**Comment by fcabrera23** [comment]
Hi @pbering,

Thanks for reaching out. We will try to reproduce this issue and reach back to you.

Thanks,
Francisco

**Comment by fcabrera23** [comment]
Hi @pbering,

Sorry for the delay - After working with the team, we decided this scenario is by design.  We will add a note in our documentation to keep a copy of other existing kubconfig files before deploying AKS-EE. If you want, after AKS-EE deployment is finished, you can manually merge your kubeconfig files and use the context option to target your different clusters.

Thanks,
Francisco
