### ISSUE TITLE
[BUG] wssdagent for EFLOW can not be installed

### ISSUE THREAD

**Issue by cburdea** [Azure/AKS-Edge#33]
Following the [quickstart guide](https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-edge-howto-single-node-deployment) on a Windows 10 Pro Azure VM for a single node deployment. 

When running `New-AksEdgeDeployment -JsonConfigFilePath .\aksedge-config.json` I get stuck with with the following error message: 

 ```
[12/27/2022` 17:00:33] Checking for virtual switch with name 'aksedgesw-int'

 - The virtual switch 'aksedgesw-int' of type 'Internal' is present
Start-Service : Service 'WSSD Agent Service (wssdagent)' cannot be started due to the following error: Cannot start service wssdagent on computer '.'.
At C:\Program Files\WindowsPowerShell\Modules\AksEdge\0.7.22335.1024\AzureEFLOW.psm1:2051 char:13
+             Start-Service -Name wssdagent
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service], ServiceCommandException
    + FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Commands.StartServiceCommand


[12/27/2022 17:00:48] Exception caught!!!

 - Time out has expired and the operation has not been completed. (L2055)

[12/27/2022` 17:00:48] In order to attempt another deployment, please uninstall AKS Edge Essentials - K8s (Public Preview) and start from fresh

 - Initialization of host services failed: Time out has expired and the operation has not been completed. at line 2608

```
 

**Environment:**
 - AKS Edge Essentials Version: 0.7.22335.1024
 - Powershell Version:  5.1.19041.2364
 - Windows Host OS:
    - Edition: Windows 10 Pro
    - Version: 10.0.19044
    - Virtual Machine: AzureVM DS3 v2

**Comment by JuergenSchwertl** [comment]
Same issue using Azure VM with Windows 11 22H2. Hyper-V on fresh VM installed using 
**enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All**

Both Windows Powershell and Powershell 7.3.1 fail on New-AksEdgeDeployment due to "wssdagent" not starting:

_Start-Service : Service 'WSSD Agent Service (wssdagent)' cannot be started due to the following error: Cannot start
service wssdagent on computer '.'.
At C:\Program Files\WindowsPowerShell\Modules\AksEdge\0.7.22335.1024\AzureEFLOW.psm1:2051 char:13
+             Start-Service -Name wssdagent
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service],
   ServiceCommandException
    + FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Commands.StartServiceCommand_

Full install output:
[WinPS5_Output.txt](https://github.com/Azure/AKS-Edge/files/10331963/WinPS5_Output.txt)
[PS7_Output.txt](https://github.com/Azure/AKS-Edge/files/10331964/PS7_Output.txt)

EventLog shows Event ID 7023 followed by 7001:
**Event ID 7023**
"The HV Host Service service terminated with the following error: 
The system cannot find the file specified."
Log Name:      System
Source:        Service Control Manager
Date:          02.01.2023 13:26:49
Event ID:      7023
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      js-de-aksnode
Description:
The HV Host Service service terminated with the following error: 
The system cannot find the file specified.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Service Control Manager" Guid="{555908d1-a6d7-4695-8e1e-26931d2012f4}" EventSourceName="Service Control Manager" />
    <EventID Qualifiers="49152">7023</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8080000000000000</Keywords>
    <TimeCreated SystemTime="2023-01-02T12:26:49.4892897Z" />
    <EventRecordID>1101</EventRecordID>
    <Correlation />
    <Execution ProcessID="892" ThreadID="4380" />
    <Channel>System</Channel>
    <Computer>js-de-aksnode</Computer>
    <Security />
  </System>
  <EventData>
    <Data Name="param1">HV Host Service</Data>
    <Data Name="param2">%%2</Data>
    <Binary>4800760048006F00730074000000</Binary>
  </EventData>
</Event>

**Event ID 7001** 
"The WSSD Agent Service service depends on the HV Host Service service which failed to start because of the following error: 
The system cannot find the file specified."

Log Name:      System
Source:        Service Control Manager
Date:          02.01.2023 13:26:49
Event ID:      7001
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      js-de-aksnode
Description:
The WSSD Agent Service service depends on the HV Host Service service which failed to start because of the following error: 
The system cannot find the file specified.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Service Control Manager" Guid="{555908d1-a6d7-4695-8e1e-26931d2012f4}" EventSourceName="Service Control Manager" />
    <EventID Qualifiers="49152">7001</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8080000000000000</Keywords>
    <TimeCreated SystemTime="2023-01-02T12:26:49.4892897Z" />
    <EventRecordID>1102</EventRecordID>
    <Correlation />
    <Execution ProcessID="892" ThreadID="7216" />
    <Channel>System</Channel>
    <Computer>js-de-aksnode</Computer>
    <Security />
  </System>
  <EventData>
    <Data Name="param1">WSSD Agent Service</Data>
    <Data Name="param2">HV Host Service</Data>
    <Data Name="param3">%%2</Data>
    <Binary>77007300730064006100670065006E0074000000</Binary>
  </EventData>
</Event>

**Comment by JuergenSchwertl** [comment]
Bummer, the used "Standard_B4m" in my case doesn't support nested virtualization (see [Azure Compute - B-Series](https://learn.microsoft.com/en-us/azure/virtual-machines/sizes-b-series-burstable) ) => thus Hyper-V fails to start. 
AksEdgeShell.ps1 (i.e. the underlying AksEdgeDeploy.psm1::Get-AideHostPcInfo) incorrectly states nested Hyper-V to be enabled when it is apparently not:
_"Running as a virtual machine in Azure environment (Name= js-de-aksnodevmSize= Standard_B4msoffer= windows-11sku= win11-21h2-pro )with Nested Hyper-V enabled"_

Even re-sizing the _existing_ VM to D4s_v3 apparently doesn't seem to re-enable Hyper-V.

**Comment by fcabrera23** [comment]
Hi @cburdea,

Thanks for your detailed information. Could you please share the installation logs? Also, could you try using Hyper-V manager to create a simple VM and see if your nested virtualization configuration works?

Thanks,
Francisco

**Comment by fcabrera23** [comment]
Hi @JuergenSchwertl,

Thanks for your information.  We will try to see if there's a way to improve the check to avoid non-supported VM sizes.  

Also, after you resized the VM, did you try disabling and enabling back again Hyper-V and see if that fixes your issue?

Thanks,
Francisco

**Comment by JuergenSchwertl** [comment]
Hi @fcabrera23 ,
I didn't remove the windows feature and installed again but tried both the PowerShell and DISM route to enable the feature again on the online image (which apparently didn't change anything as it was already installed but non-functional). Installing a wsl2 distro still broke as well.
Caveat is that I deleted the VM already and created a new one as Standard_Ds4_v3 then hitting #34 and #35 

Cheers, Juergen

**Comment by fcabrera23** [comment]
Hi @JuergenSchwertl,

I have just tested your scenario. If you resize the VM to a supported SKU, followed by a disabling of hyper-v (reboot needed) and enable hyper-v back again (reboot needed), the WSSDAgent will start and you can continue with AKS Edge installation.

As far as I know, from the Azure VM Windows OS, we cannot know if the VM SKU used supports or not virtualization unless we compare it with the public documentation. We will try to see if we can address this in the future. 

Thanks,
Francisco

**Comment by fcabrera23** [comment]
Hi @cburdea,

I just double-checked the information provided. The DSV2 series you're using does NOT support Nested Virtualization. For more information, check [Dv2 and DSv2 series](https://learn.microsoft.com/en-us/azure/virtual-machines/dv2-dsv2-series). 

Please try again with an Azure VM series that supports nested virtualization, for example, D8s_v3.

Thanks,
Francisco

**Comment by JuergenSchwertl** [comment]
Hi @fcabrera23 ,

As there seems currently no way to programmatically verify if the VM supports nested virtualization, but you still can identify that you actually run in an Azure VM environment I'd suggest to tell the user that nested Hyper-V virtualization support cannot be validated and point the user to the docs page to validate. i.e.
 
_"Running as a **virtual machine in Azure environment** (Name= js-de-aksnodevmSize= Standard_B4msoffer= windows-11sku= win11-21h2-pro ) **Nested Hyper-V support not validated** Pls. see https://learn.microsoft.com/en-us/azure/virtual-machines/sizes-general and following to validate if your VM supports nested virtualization"_

**Comment by fcabrera23** [comment]
Hi @JuergenSchwertl,

Great suggestion. We will consider this messaging improvement for the upcoming updates.

Thanks,
Francisco

**Comment by luukdekinderenIS** [comment]
I encountered a similar issue during the installation of IoT Edge. I received the error message: **Failed to start service 'WSSD Agent Service (wssdagent)'**.

It’s important to note that I don’t think my issue is the same as the one described above. However, I wanted to share my findings here in case someone is searching for solutions related to problems with the WSSD Agent. My solution might be helpful in their situation. Here’s what I did:

I checked the file located at `C:\ProgramData\wssdagent\log\wssdagent.log`. In the log, I found a line indicating that the following file was being read:  
`C:\ProgramData\wssdagent\v0.10.8-alpha.10\config.yaml`.  

However, that file didn’t exist at all, and there where no other logs in de logfile. I copied the file from another computer with IoT Edge installed, and afterward, I was able to complete the IoT Edge installation successfully.

Why this issue occurred on this specific machine remains a mystery to me. Even after a complete reinstallation of Windows, the problem persisted. And a manual copy of the file is needed. I hope this post is helpful to someone! Good luck.
